version: '3.7'
services:
  msCompte:
    container_name: msCompte
    image: flav1ann/mscompte:v1
    ports:
      - 8083:8083
    restart: always
    networks:
      - spring-boot-network
networks:
  spring-boot-network:
    name: spring-boot-network
    driver: bridge
