FROM maven:3.8.4-openjdk-11-slim as build
RUN mkdir msConfig
WORKDIR /msConfig
COPY ./ ./
RUN mvn clean package spring-boot:repackage
RUN ls
RUN ls ./target

FROM gcr.io/distroless/java:11
COPY --from=build /msConfig/target/*.jar /jar-files/msConfig.jar
WORKDIR /jar-files

EXPOSE 8888
CMD [ "msConfig.jar" ]